// config/reviewForm.js
function generateReviewForm(clientId, bizName, logoUrl, brandColor) {
  var color = brandColor || '#6366f1';
  var logoHTML = logoUrl
    ? '<div style="text-align:center;margin-bottom:24px;"><img src="' + logoUrl + '" style="max-height:70px;max-width:220px;" alt="logo"></div>'
    : '<div style="text-align:center;font-size:20px;font-weight:700;color:#0f172a;margin-bottom:20px;">' + bizName + '</div>';

  var html = [];
  html.push('<!DOCTYPE html>');
  html.push('<html lang="en">');
  html.push('<head>');
  html.push('<meta charset="UTF-8">');
  html.push('<meta name="viewport" content="width=device-width, initial-scale=1.0">');
  html.push('<title>Rate Your Experience - ' + bizName + '</title>');
  html.push('<style>');
  html.push('body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; background: #f8fafc; min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 20px; margin: 0; }');
  html.push('.card { background: white; border-radius: 16px; padding: 40px; max-width: 480px; width: 100%; box-shadow: 0 4px 20px rgba(0,0,0,0.08); }');
  html.push('h1 { font-size: 22px; color: #0f172a; margin: 0 0 8px 0; }');
  html.push('p { color: #64748b; font-size: 15px; line-height: 1.6; margin: 0 0 24px 0; }');
  html.push('.star-row { display: flex; gap: 8px; justify-content: center; margin: 0 0 8px 0; }');
  html.push('.star { font-size: 52px; color: #d1d5db; cursor: pointer; line-height: 1; padding: 4px; border: none; background: none; transition: color 0.1s; }');
  html.push('.star:hover { transform: scale(1.1); }');
  html.push('.star-msg { text-align: center; font-size: 14px; color: #6366f1; min-height: 24px; margin-bottom: 16px; font-weight: 600; }');
  html.push('.low-msg { background: #fef3c7; border: 1px solid #f59e0b; border-radius: 10px; padding: 14px; margin-bottom: 16px; font-size: 13px; color: #92400e; display: none; }');
  html.push('label { font-size: 11px; font-weight: 700; color: #64748b; text-transform: uppercase; letter-spacing: 0.05em; display: block; margin-bottom: 8px; }');
  html.push('input, textarea { width: 100%; border: 1.5px solid #e2e8f0; border-radius: 10px; padding: 12px 14px; font-size: 14px; font-family: inherit; color: #0f172a; margin-bottom: 14px; display: block; box-sizing: border-box; }');
  html.push('textarea { min-height: 110px; resize: vertical; }');
  html.push('input:focus, textarea:focus { outline: none; border-color: ' + color + '; }');
  html.push('.submit-btn { width: 100%; background: ' + color + '; color: white; border: none; border-radius: 10px; padding: 14px; font-size: 15px; font-weight: 600; cursor: pointer; font-family: inherit; }');
  html.push('.submit-btn:disabled { opacity: 0.4; cursor: not-allowed; }');
  html.push('.success { text-align: center; padding: 20px 0; display: none; }');
  html.push('.success-icon { font-size: 64px; margin-bottom: 16px; }');
  html.push('</style>');
  html.push('</head>');
  html.push('<body>');
  html.push('<div class="card">');
  html.push('<div id="form-section">');
  html.push(logoHTML);
  html.push('<h1>How was your visit?</h1>');
  html.push('<p>Your feedback helps ' + bizName + ' serve you better. Takes less than a minute.</p>');
  html.push('<label>Your Rating</label>');
  html.push('<div class="star-row">');
  html.push('<button class="star" id="star1" data-val="1" type="button">&#9733;</button>');
  html.push('<button class="star" id="star2" data-val="2" type="button">&#9733;</button>');
  html.push('<button class="star" id="star3" data-val="3" type="button">&#9733;</button>');
  html.push('<button class="star" id="star4" data-val="4" type="button">&#9733;</button>');
  html.push('<button class="star" id="star5" data-val="5" type="button">&#9733;</button>');
  html.push('</div>');
  html.push('<div class="star-msg" id="star-msg"></div>');
  html.push('<div class="low-msg" id="low-msg">We\'re sorry to hear that. Your feedback goes directly to the team privately and will never be posted publicly.</div>');
  html.push('<label>Your Name</label>');
  html.push('<input type="text" id="author" placeholder="First name">');
  html.push('<label>Tell Us About Your Experience</label>');
  html.push('<textarea id="review-text" placeholder="What did you love? What could we improve?"></textarea>');
  html.push('<button class="submit-btn" id="submit-btn" disabled type="button">Submit Review</button>');
  html.push('</div>');
  html.push('<div class="success" id="success-section">');
  html.push('<div class="success-icon">&#11088;</div>');
  html.push('<h1>Thank you!</h1>');
  html.push('<p style="margin-top: 12px;">Your feedback means a lot to the team at ' + bizName + '.</p>');
  html.push('</div>');
  html.push('</div>');
  html.push('<script>');
  html.push('(function() {');
  html.push('  var selectedRating = 0;');
  html.push('  var clientId = "' + clientId + '";');
  html.push('  var labels = { 1: "Poor", 2: "Fair", 3: "Good", 4: "Great", 5: "Excellent!" };');
  html.push('');
  html.push('  function paintStars(n) {');
  html.push('    for (var i = 1; i <= 5; i++) {');
  html.push('      var el = document.getElementById("star" + i);');
  html.push('      el.style.color = i <= n ? "#f59e0b" : "#d1d5db";');
  html.push('    }');
  html.push('  }');
  html.push('');
  html.push('  function checkSubmit() {');
  html.push('    var hasRating = selectedRating > 0;');
  html.push('    var hasName = document.getElementById("author").value.trim().length > 1;');
  html.push('    var hasText = document.getElementById("review-text").value.trim().length > 10;');
  html.push('    document.getElementById("submit-btn").disabled = !(hasRating && hasName && hasText);');
  html.push('  }');
  html.push('');
  html.push('  for (var i = 1; i <= 5; i++) {');
  html.push('    (function(num) {');
  html.push('      document.getElementById("star" + num).addEventListener("click", function(e) {');
  html.push('        e.preventDefault();');
  html.push('        selectedRating = num;');
  html.push('        paintStars(num);');
  html.push('        document.getElementById("star-msg").textContent = labels[num];');
  html.push('        document.getElementById("low-msg").style.display = num < 5 ? "block" : "none";');
  html.push('        checkSubmit();');
  html.push('      });');
  html.push('      document.getElementById("star" + num).addEventListener("mouseover", function() {');
  html.push('        paintStars(num);');
  html.push('        document.getElementById("star-msg").textContent = labels[num];');
  html.push('      });');
  html.push('      document.getElementById("star" + num).addEventListener("mouseout", function() {');
  html.push('        paintStars(selectedRating);');
  html.push('        document.getElementById("star-msg").textContent = selectedRating ? labels[selectedRating] : "";');
  html.push('      });');
  html.push('    })(i);');
  html.push('  }');
  html.push('');
  html.push('  document.getElementById("author").addEventListener("input", checkSubmit);');
  html.push('  document.getElementById("review-text").addEventListener("input", checkSubmit);');
  html.push('');
  html.push('  document.getElementById("submit-btn").addEventListener("click", function() {');
  html.push('    var btn = document.getElementById("submit-btn");');
  html.push('    btn.disabled = true;');
  html.push('    btn.textContent = "Submitting...";');
  html.push('    fetch("/api/clients/" + clientId + "/screening/submit", {');
  html.push('      method: "POST",');
  html.push('      headers: { "Content-Type": "application/json" },');
  html.push('      body: JSON.stringify({');
  html.push('        author: document.getElementById("author").value.trim(),');
  html.push('        rating: selectedRating,');
  html.push('        text: document.getElementById("review-text").value.trim()');
  html.push('      })');
  html.push('    }).then(function() {');
  html.push('      document.getElementById("form-section").style.display = "none";');
  html.push('      document.getElementById("success-section").style.display = "block";');
  html.push('    }).catch(function() {');
  html.push('      btn.disabled = false;');
  html.push('      btn.textContent = "Try again";');
  html.push('    });');
  html.push('  });');
  html.push('})();');
  html.push('</script>');
  html.push('</body>');
  html.push('</html>');
  return html.join('\n');
}

module.exports = { generateReviewForm };
