// config/reviewForm.js v4
function generateReviewForm(clientId, bizName, logoUrl, brandColor) {
  var color = brandColor || '#6366f1';
  var logoHTML = logoUrl
    ? '<div style="text-align:center;margin-bottom:24px;"><img src="' + logoUrl + '" style="max-height:70px;max-width:220px;" alt="logo"></div>'
    : '<div style="text-align:center;font-size:20px;font-weight:700;color:#0f172a;margin-bottom:20px;">' + bizName + '</div>';

  var html = [];
  html.push('<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8">');
  html.push('<meta name="viewport" content="width=device-width, initial-scale=1.0">');
  html.push('<title>Rate Your Experience - ' + bizName + '</title>');
  html.push('<style>');
  html.push('body{font-family:sans-serif;background:#f8fafc;min-height:100vh;display:flex;align-items:center;justify-content:center;padding:20px;margin:0}');
  html.push('.card{background:white;border-radius:16px;padding:40px;max-width:480px;width:100%;box-shadow:0 4px 20px rgba(0,0,0,.08)}');
  html.push('h1{font-size:22px;color:#0f172a;margin:0 0 8px}');
  html.push('p.sub{color:#64748b;font-size:15px;line-height:1.6;margin:0 0 24px}');
  html.push('.lbl{font-size:11px;font-weight:700;color:#64748b;text-transform:uppercase;letter-spacing:.05em;display:block;margin-bottom:8px}');
  html.push('.stars{display:flex;gap:8px;justify-content:center;margin-bottom:8px}');
  html.push('.st{font-size:52px;cursor:pointer;line-height:1;background:none;border:none;padding:4px;color:rgb(209,213,219)}');
  html.push('.st.on{color:rgb(245,158,11)}');
  html.push('.smsg{text-align:center;font-size:14px;color:#6366f1;font-weight:600;min-height:24px;margin-bottom:16px}');
  html.push('.lmsg{background:#fef3c7;border:1px solid #f59e0b;border-radius:10px;padding:14px;margin-bottom:16px;font-size:13px;color:#92400e;display:none}');
  html.push('input,textarea{width:100%;border:1.5px solid #e2e8f0;border-radius:10px;padding:12px 14px;font-size:14px;margin-bottom:14px;display:block;box-sizing:border-box;font-family:inherit}');
  html.push('textarea{min-height:110px;resize:vertical}');
  html.push('.btn{width:100%;background:' + color + ';color:white;border:none;border-radius:10px;padding:14px;font-size:15px;font-weight:600;cursor:pointer;font-family:inherit}');
  html.push('.btn:disabled{opacity:.4;cursor:not-allowed}');
  html.push('.done{text-align:center;padding:20px 0;display:none}');
  html.push('</style></head><body>');
  html.push('<div class="card">');
  html.push('<div id="FS">');
  html.push(logoHTML);
  html.push('<h1>How was your visit?</h1>');
  html.push('<p class="sub">Your feedback helps ' + bizName + ' serve you better.</p>');
  html.push('<span class="lbl">Your Rating</span>');
  html.push('<div class="stars">');
  html.push('<button class="st" id="s1" type="button">&#9733;</button>');
  html.push('<button class="st" id="s2" type="button">&#9733;</button>');
  html.push('<button class="st" id="s3" type="button">&#9733;</button>');
  html.push('<button class="st" id="s4" type="button">&#9733;</button>');
  html.push('<button class="st" id="s5" type="button">&#9733;</button>');
  html.push('</div>');
  html.push('<div class="smsg" id="SM"></div>');
  html.push('<div class="lmsg" id="LM">We\'re sorry to hear that. Your feedback goes directly to the team privately and will never be posted publicly.</div>');
  html.push('<span class="lbl">Your Name</span>');
  html.push('<input type="text" id="AU" placeholder="First name">');
  html.push('<span class="lbl">Your Experience</span>');
  html.push('<textarea id="TX" placeholder="What did you love? What could we improve?"></textarea>');
  html.push('<button class="btn" id="BT" type="button" disabled>Submit Review</button>');
  html.push('</div>');
  html.push('<div class="done" id="DN">');
  html.push('<div style="font-size:64px;margin-bottom:16px">&#11088;</div>');
  html.push('<h1>Thank you!</h1>');
  html.push('<p class="sub" style="margin-top:12px">Your feedback means a lot to ' + bizName + '.</p>');
  html.push('</div>');
  html.push('</div>');
  html.push('<script>');
  html.push('var r=0,cid="' + clientId + '";');
  html.push('var lb=["","Poor","Fair","Good","Great","Excellent!"];');
  html.push('var ON="rgb(245,158,11)",OFF="rgb(209,213,219)";');
  html.push('function paint(n){');
  html.push('  for(var j=1;j<=5;j++){');
  html.push('    var el=document.getElementById("s"+j);');
  html.push('    el.style.color=j<=n?ON:OFF;');
  html.push('  }');
  html.push('}');
  html.push('function chk(){');
  html.push('  var ok=r>0&&document.getElementById("AU").value.trim().length>1&&document.getElementById("TX").value.trim().length>10;');
  html.push('  document.getElementById("BT").disabled=!ok;');
  html.push('}');
  html.push('for(var i=1;i<=5;i++){');
  html.push('  (function(n){');
  html.push('    document.getElementById("s"+n).addEventListener("click",function(){');
  html.push('      r=n;paint(n);');
  html.push('      document.getElementById("SM").textContent=lb[n];');
  html.push('      document.getElementById("LM").style.display=n<5?"block":"none";');
  html.push('      chk();');
  html.push('    });');
  html.push('  })(i);');
  html.push('}');
  html.push('document.getElementById("AU").addEventListener("input",chk);');
  html.push('document.getElementById("TX").addEventListener("input",chk);');
  html.push('document.getElementById("BT").addEventListener("click",function(){');
  html.push('  var b=document.getElementById("BT");');
  html.push('  b.disabled=true;b.textContent="Submitting...";');
  html.push('  fetch("/api/clients/"+cid+"/screening/submit",{');
  html.push('    method:"POST",headers:{"Content-Type":"application/json"},');
  html.push('    body:JSON.stringify({author:document.getElementById("AU").value.trim(),rating:r,text:document.getElementById("TX").value.trim()})');
  html.push('  }).then(function(){');
  html.push('    document.getElementById("FS").style.display="none";');
  html.push('    document.getElementById("DN").style.display="block";');
  html.push('  }).catch(function(){b.disabled=false;b.textContent="Try again";});');
  html.push('});');
  html.push('</script></body></html>');
  return html.join('\n');
}
module.exports = { generateReviewForm };
